version: "3.9"

services:
  avalanche:
    image: avaplatform/avalanchego
    container_name: "rpc-avalanche"
    #command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    command:
      [
        "/avalanchego/build/avalanchego",
        "--db-dir=/data",
        "--bootstrap-ancestors-max-containers-received=10000",
        "--index-enabled=true",
      ]
    ports:
      - 127.0.0.1:33650:9650
      - 127.0.0.1:33651:9651
    volumes:
      - /opt/nodes/avalanche/data:/data
    restart: unless-stopped
